# Generated by Django 6.0.2 on 2026-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen'),
        ),
    ]
