# Generated by Django 6.0.2 on 2026-05-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha']},
        ),
    ]
